title: SIEMplified
#email: youremail@example.com
description: >-
  A blog dedicated to simplifying SIEM technologies.
baseurl: "/SIEMplified"
url: "https://4mitSurya.github.io"

remote_theme: LeNPaul/lagrange

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown

author:
  name: Your Name

social:
  github: yourgithubusername
  linkedin: yourlinkedinusername
  email: youremail@example.com
